import { StyleSheet } from 'react-native';

// ═══════════════════════════════════════════════════════════════════════════════
// 2026 Dark-Mode Design System — "Midnight Luxe"
// Inspired by Netflix / TikTok / X dark themes
// ═══════════════════════════════════════════════════════════════════════════════

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0A0A12',
  },
  container: {
    padding: 16,
    paddingBottom: 30,
  },
  scrollContent: {
    backgroundColor: '#0A0A12',
  },
  homeScrollContent: {
    flexGrow: 1,
    paddingBottom: 100,
  },

  // ─── Header ──────────────────────────────────────────────────────────────────
  headerBg: {
    height: 270,
    justifyContent: 'space-between',
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 22,
  },
  headerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(10, 10, 18, 0.72)',
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 10,
  },
  levelBadge: {
    backgroundColor: 'rgba(139, 92, 246, 0.18)',
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.35)',
  },
  levelBadgeText: {
    color: '#C4B5FD',
    fontWeight: '600',
    fontSize: 14,
  },
  levelBadgeLevel: {
    color: '#A78BFA',
    fontWeight: '800',
    fontSize: 16,
    marginTop: 2,
  },
  avatarCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'rgba(139, 92, 246, 0.5)',
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 6,
  },
  avatarText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  headerContent: {
    zIndex: 10,
  },
  welcomeTitle: {
    color: '#F1F5F9',
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  welcomeSub: {
    color: 'rgba(241, 245, 249, 0.55)',
    fontSize: 14,
    fontWeight: '500',
  },

  // ─── CTA Button ──────────────────────────────────────────────────────────────
  ctaButton: {
    flexDirection: 'row',
    backgroundColor: '#8B5CF6',
    borderRadius: 20,
    padding: 18,
    marginHorizontal: 16,
    marginTop: -26,
    marginBottom: 24,
    alignItems: 'center',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 14,
  },
  ctaButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  ctaButtonSub: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    marginTop: 2,
    fontWeight: '500',
  },
  listenCtaButton: {
    backgroundColor: 'transparent',
    shadowColor: '#06B6D4',
  },

  // ─── Interview CTA ───────────────────────────────────────────────────────────
  interviewCtaButton: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    borderRadius: 20,
    padding: 18,
    marginHorizontal: 16,
    marginBottom: 24,
    alignItems: 'center',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 14,
  },
  interviewCtaButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  interviewCtaButtonSub: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '500',
  },

  // ─── Stats Grid ──────────────────────────────────────────────────────────────
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: 16,
    marginBottom: 24,
    gap: 12,
  },
  statCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#12121E',
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    borderLeftWidth: 3,
    alignItems: 'center',
  },
  statLabel: {
    color: '#64748B',
    fontSize: 12,
    marginTop: 8,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  statValue: {
    fontSize: 26,
    fontWeight: '800',
    color: '#F1F5F9',
    marginTop: 4,
  },

  // ─── Cards ────────────────────────────────────────────────────────────────────
  card: {
    backgroundColor: '#12121E',
    borderRadius: 20,
    padding: 18,
    marginHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  adaptiveCard: {
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
    backgroundColor: '#14141F',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginLeft: 12,
    color: '#F1F5F9',
  },
  progressItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressLabel: {
    color: '#94A3B8',
    fontWeight: '600',
  },
  trendBadge: {
    flexDirection: 'row',
    backgroundColor: 'rgba(52, 211, 153, 0.15)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: 'center',
  },
  trendText: {
    color: '#34D399',
    fontWeight: 'bold',
    marginLeft: 4,
  },
  milestoneText: {
    color: '#64748B',
    fontSize: 13,
    marginTop: 4,
  },
  confidenceText: {
    color: '#475569',
    fontSize: 11,
    marginTop: 12,
    fontStyle: 'italic',
  },

  // ─── Quick Actions ────────────────────────────────────────────────────────────
  quickActionsSection: {
    marginHorizontal: 16,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#F1F5F9',
    marginBottom: 14,
    letterSpacing: -0.3,
  },
  actionButton: {
    flexDirection: 'row',
    backgroundColor: '#12121E',
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  actionButtonText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#F1F5F9',
    marginLeft: 12,
  },

  // ─── Achievements ─────────────────────────────────────────────────────────────
  achievementsSection: {
    marginHorizontal: 16,
    marginBottom: 24,
  },
  achievementGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  achievementBadge: {
    backgroundColor: '#12121E',
    borderRadius: 16,
    padding: 14,
    width: '31%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  achievementEmoji: {
    fontSize: 32,
    marginBottom: 4,
  },
  achievementName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#CBD5E1',
    textAlign: 'center',
  },

  // ─── Quiz ─────────────────────────────────────────────────────────────────────
  quizHeader: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#0E0E18',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  quizTopActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  quizActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(139, 92, 246, 0.15)',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.25)',
  },
  quizActionText: {
    color: '#A78BFA',
    fontWeight: '700',
    marginLeft: 6,
  },
  listenControlsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  listenControlButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(6, 182, 212, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(6, 182, 212, 0.25)',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
  },
  listenControlText: {
    marginLeft: 6,
    color: '#67E8F9',
    fontWeight: '700',
    fontSize: 12,
  },
  listenAutoAdvanceBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(139, 92, 246, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.25)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 8,
    gap: 6,
  },
  listenAutoAdvanceText: {
    flex: 1,
    color: '#C4B5FD',
    fontSize: 12,
    fontWeight: '600',
  },
  listenAutoAdvanceCancelBtn: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    backgroundColor: 'rgba(139, 92, 246, 0.25)',
    borderRadius: 8,
  },
  listenAutoAdvanceCancelText: {
    color: '#A78BFA',
    fontSize: 11,
    fontWeight: '700',
  },
  progressBar: {
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#8B5CF6',
  },
  progressText: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '700',
    textAlign: 'right',
  },
  quizContent: {
    flex: 1,
    backgroundColor: '#0A0A12',
  },
  quizContainer: {
    padding: 16,
    paddingBottom: 30,
  },
  questionText: {
    fontSize: 22,
    fontWeight: '800',
    color: '#F1F5F9',
    marginBottom: 18,
    lineHeight: 30,
    letterSpacing: -0.3,
  },
  hintBox: {
    flexDirection: 'row',
    backgroundColor: 'rgba(251, 191, 36, 0.1)',
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.2)',
  },
  hintText: {
    color: '#FCD34D',
    marginLeft: 10,
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
  },
  optionsContainer: {
    gap: 10,
  },
  optionButton: {
    flexDirection: 'row',
    backgroundColor: '#12121E',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  optionSelected: {
    borderColor: '#8B5CF6',
    backgroundColor: 'rgba(139, 92, 246, 0.12)',
  },
  optionCorrect: {
    borderColor: '#34D399',
    backgroundColor: 'rgba(52, 211, 153, 0.12)',
  },
  optionWrong: {
    borderColor: '#F87171',
    backgroundColor: 'rgba(248, 113, 113, 0.12)',
  },
  optionDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    marginRight: 10,
  },
  optionText: {
    flex: 1,
    fontSize: 16,
    color: '#CBD5E1',
    fontWeight: '600',
  },
  optionCorrectText: {
    color: '#34D399',
  },
  optionWrongText: {
    color: '#F87171',
  },
  feedbackBox: {
    marginTop: 20,
    backgroundColor: '#12121E',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  feedbackCorrect: {
    fontSize: 18,
    fontWeight: '800',
    color: '#34D399',
    marginTop: 8,
  },
  feedbackWrong: {
    fontSize: 14,
    color: '#94A3B8',
    marginTop: 8,
  },
  feedbackAnswer: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F87171',
    marginTop: 4,
  },

  // ─── Review ───────────────────────────────────────────────────────────────────
  reviewContainer: {
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  celebrationBox: {
    backgroundColor: '#12121E',
    borderRadius: 24,
    padding: 36,
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.15)',
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  celebrationEmoji: {
    fontSize: 64,
    marginBottom: 14,
  },
  scoreTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#F1F5F9',
    letterSpacing: -0.3,
  },
  scoreValue: {
    fontSize: 52,
    fontWeight: '900',
    color: '#8B5CF6',
    marginVertical: 8,
  },
  scorePercent: {
    fontSize: 34,
    fontWeight: '900',
    color: '#34D399',
    marginBottom: 12,
  },
  praises: {
    fontSize: 16,
    color: '#94A3B8',
    fontStyle: 'italic',
    marginTop: 12,
  },
  weakCard: {
    marginHorizontal: 0,
    marginBottom: 20,
  },
  weakItem: {
    marginBottom: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  weakTopic: {
    fontSize: 14,
    fontWeight: '700',
    color: '#F1F5F9',
    marginBottom: 6,
  },
  weakBar: {
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 4,
  },
  weakBarFill: {
    height: '100%',
    backgroundColor: '#F87171',
  },
  weakPercent: {
    fontSize: 12,
    color: '#64748B',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
  },
  button: {
    flex: 1,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  buttonPrimary: {
    backgroundColor: '#8B5CF6',
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  buttonSecondary: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#F1F5F9',
  },

  // ─── Page ─────────────────────────────────────────────────────────────────────
  pageTitle: {
    fontSize: 30,
    fontWeight: '800',
    color: '#F1F5F9',
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  pageSubtitle: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 20,
    fontWeight: '500',
  },

  // ─── Mode Card ────────────────────────────────────────────────────────────────
  modeCard: {
    flexDirection: 'row',
    backgroundColor: '#12121E',
    borderRadius: 20,
    padding: 18,
    marginBottom: 12,
    alignItems: 'center',
    borderLeftWidth: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  modeIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modeIconText: {
    fontSize: 28,
  },
  modeContent: {
    flex: 1,
    marginLeft: 14,
  },
  modeTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#F1F5F9',
  },
  modeDesc: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 3,
    fontWeight: '500',
  },
  modeFilterCard: {
    backgroundColor: '#12121E',
    borderRadius: 20,
    padding: 18,
    marginTop: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  modeFilterTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#F1F5F9',
  },
  modeFilterHint: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 4,
    marginBottom: 10,
  },
  modeFilterLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#94A3B8',
    marginBottom: 6,
  },
  modeFilterSummary: {
    marginTop: 12,
    fontSize: 13,
    color: '#34D399',
    fontWeight: '700',
  },
  modeStartButton: {
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 18,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#8B5CF6',
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 6,
  },
  modeStartButtonText: {
    color: '#fff',
    marginLeft: 8,
    fontSize: 16,
    fontWeight: '800',
  },

  // ─── Case Progress ────────────────────────────────────────────────────────────
  caseCard: {
    backgroundColor: '#12121E',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  caseHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  caseTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#F1F5F9',
  },
  casePct: {
    fontSize: 16,
    fontWeight: '800',
    color: '#38BDF8',
  },
  caseSubtext: {
    marginTop: 8,
    color: '#64748B',
    fontSize: 13,
  },
  caseProgressTrack: {
    marginTop: 12,
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
  },
  caseProgressFill: {
    height: '100%',
    backgroundColor: '#38BDF8',
  },
  casePortalButton: {
    marginTop: 14,
    backgroundColor: '#1A1A2A',
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  casePortalButtonText: {
    color: '#F1F5F9',
    fontWeight: '700',
    marginLeft: 8,
  },
  caseLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#94A3B8',
    marginBottom: 6,
  },
  caseActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  caseSaveButton: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: '#8B5CF6',
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 3,
  },
  caseSaveButtonText: {
    color: '#fff',
    fontWeight: '700',
    marginLeft: 8,
  },
  caseResetButton: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    paddingHorizontal: 16,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  caseResetButtonText: {
    color: '#A78BFA',
    fontWeight: '700',
    marginLeft: 6,
  },
  caseTimelineItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  caseTimelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 6,
    marginRight: 10,
    backgroundColor: '#38BDF8',
  },
  caseTimelineStage: {
    fontSize: 14,
    fontWeight: '700',
    color: '#F1F5F9',
  },
  caseTimelineStatus: {
    fontSize: 13,
    color: '#94A3B8',
    marginTop: 2,
  },
  caseTimelineDate: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  caseChecklistItem: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  caseChecklistText: {
    marginLeft: 8,
    color: '#CBD5E1',
    fontSize: 13,
    flex: 1,
    lineHeight: 18,
  },
  caseSecondaryButton: {
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  caseSecondaryButtonText: {
    marginLeft: 8,
    color: '#F1F5F9',
    fontWeight: '700',
  },

  // ─── Mastery Map ──────────────────────────────────────────────────────────────
  masteryOverviewCard: {
    backgroundColor: '#12121E',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  masteryOverviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  masteryMetric: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  masteryMetricValue: {
    fontSize: 26,
    fontWeight: '900',
    color: '#F1F5F9',
  },
  masteryMetricLabel: {
    marginTop: 2,
    fontSize: 12,
    color: '#64748B',
    textAlign: 'center',
    fontWeight: '600',
  },
  masteryUpdatedText: {
    marginTop: 10,
    fontSize: 12,
    color: '#475569',
  },
  masteryCard: {
    backgroundColor: '#12121E',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  masteryCardTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#F1F5F9',
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  masteryEmptyText: {
    color: '#64748B',
    fontSize: 13,
  },
  masteryTopicRow: {
    marginTop: 10,
  },
  masteryDueRow: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.2)',
    backgroundColor: 'rgba(56, 189, 248, 0.06)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  masteryDueTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#7DD3FC',
  },
  masteryDueMeta: {
    marginTop: 2,
    fontSize: 12,
    color: '#38BDF8',
  },
  masteryActionButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  masteryActionButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  masteryRecommendationRow: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  masteryRecommendationMeta: {
    marginTop: 2,
    fontSize: 12,
    color: '#64748B',
  },
  masteryTopicHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  masteryTopicTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: '#F1F5F9',
    marginRight: 10,
  },
  masteryTopicMeta: {
    fontSize: 12,
    color: '#64748B',
  },
  masteryBarTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
  },
  masteryBarFill: {
    height: '100%',
    backgroundColor: '#8B5CF6',
  },
  masteryHeatItem: {
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  masteryHeatTitle: {
    fontSize: 13,
    fontWeight: '800',
  },
  masteryHeatMeta: {
    fontSize: 12,
    marginTop: 2,
  },
  masteryHeatmapWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  masteryHeatTile: {
    width: '31%',
    minWidth: 95,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  masteryHeatTilePct: {
    fontSize: 16,
    fontWeight: '900',
  },
  masteryHeatTileName: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: '700',
  },
  masteryTrendRow: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 14,
    padding: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  masteryTrendHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  masteryTrendBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  masteryTrendBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  masteryTrendMeta: {
    marginTop: 6,
    fontSize: 12,
    color: '#64748B',
  },
  masteryTrendBars: {
    marginTop: 8,
    gap: 8,
  },
  masteryTrendBarBlock: {
    gap: 4,
  },
  masteryTrendBarLabel: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '700',
  },
  masteryTrendStripRow: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 6,
  },
  masteryTrendStripCol: {
    flex: 1,
    alignItems: 'center',
  },
  masteryTrendStripTop: {
    fontSize: 10,
    color: '#64748B',
    marginBottom: 4,
    fontWeight: '700',
  },
  masteryTrendStripTrack: {
    width: '100%',
    height: 70,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  masteryTrendStripFill: {
    width: '100%',
    borderRadius: 10,
    minHeight: 6,
  },
  masteryTrendStripBottom: {
    marginTop: 4,
    fontSize: 10,
    color: '#475569',
    fontWeight: '700',
  },
  masteryUrgencyRow: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.25)',
    borderRadius: 14,
    padding: 14,
    backgroundColor: 'rgba(248, 113, 113, 0.06)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  masteryUrgencyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  masteryUrgencyBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  masteryUrgencyBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  masteryRouteRow: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.15)',
    borderRadius: 16,
    backgroundColor: 'rgba(139, 92, 246, 0.06)',
    paddingVertical: 14,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  masteryRouteStepBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 3,
  },
  masteryRouteStepBadgeText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 13,
  },
  masteryRouteRowDone: {
    borderColor: 'rgba(52, 211, 153, 0.3)',
    backgroundColor: 'rgba(52, 211, 153, 0.08)',
    opacity: 0.85,
  },
  masteryRouteConfidencePill: {
    alignSelf: 'flex-start',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginTop: 5,
  },
  masteryRouteConfidencePillText: {
    fontSize: 10,
    fontWeight: '800',
  },
  masteryActionButtonDone: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  masteryResetButton: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    paddingVertical: 14,
    marginBottom: 18,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  masteryResetButtonText: {
    marginLeft: 8,
    fontWeight: '700',
    color: '#A78BFA',
  },

  // ─── Profile ──────────────────────────────────────────────────────────────────
  profileCard: {
    backgroundColor: '#12121E',
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  profileAvatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.5,
    shadowRadius: 18,
    elevation: 8,
  },
  profileAvatarText: {
    fontSize: 36,
  },
  profileAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 42,
  },
  profileAvatarActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  profileAvatarActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(196, 181, 253, 0.35)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(139, 92, 246, 0.12)',
  },
  profileAvatarActionText: {
    marginLeft: 6,
    color: '#E2E8F0',
    fontWeight: '700',
    fontSize: 12,
  },
  profileNameEditorWrap: {
    width: '100%',
    marginBottom: 10,
  },
  profileNameInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 12,
    backgroundColor: '#0F172A',
    color: '#F8FAFC',
    paddingHorizontal: 12,
    fontSize: 13,
    fontWeight: '600',
  },
  profileName: {
    fontSize: 26,
    fontWeight: '800',
    color: '#F1F5F9',
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  profileEmail: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 20,
  },
  profileStats: {
    flexDirection: 'row',
    gap: 30,
    marginBottom: 20,
  },
  profileStat: {
    alignItems: 'center',
  },
  profileStatValue: {
    fontSize: 26,
    fontWeight: '900',
    color: '#8B5CF6',
  },
  profileStatLabel: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 4,
    fontWeight: '600',
  },
  editButton: {
    flexDirection: 'row',
    backgroundColor: '#8B5CF6',
    borderRadius: 14,
    paddingHorizontal: 22,
    paddingVertical: 13,
    alignItems: 'center',
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 4,
  },
  editButtonText: {
    color: '#fff',
    fontWeight: '800',
    marginLeft: 8,
  },

  // ─── Family ───────────────────────────────────────────────────────────────────
  familyCard: {
    flexDirection: 'row',
    backgroundColor: '#12121E',
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  familyCardLeader: {
    backgroundColor: 'rgba(251, 191, 36, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.3)',
  },
  familyRank: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FBBF24',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    shadowColor: '#FBBF24',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 3,
  },
  familyRankText: {
    fontWeight: '800',
    color: '#0A0A12',
    fontSize: 14,
  },
  familyAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  familyAvatarText: {
    color: '#fff',
    fontWeight: '800',
  },
  familyInfo: {
    flex: 1,
  },
  familyName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#F1F5F9',
  },
  familyStats: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  familyPoints: {
    alignItems: 'center',
  },
  familyPointsValue: {
    fontSize: 20,
    fontWeight: '900',
    color: '#8B5CF6',
  },
  familyPointsLabel: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '600',
  },

  // ─── Tab Bar ──────────────────────────────────────────────────────────────────
  tabBar: {
    backgroundColor: '#0E0E18',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.06)',
    height: 64,
    paddingBottom: 8,
    paddingTop: 8,
    elevation: 0,
  },

  // ─── Onboarding ───────────────────────────────────────────────────────────────
  onboardingProgress: {
    marginBottom: 32,
  },
  onboardingProgressText: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 8,
    fontWeight: '700',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#8B5CF6',
  },
  onboardingStep: {
    alignItems: 'center',
    marginBottom: 32,
  },
  onboardingIcon: {
    fontSize: 64,
    marginBottom: 16,
  },
  onboardingTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#F1F5F9',
    marginBottom: 8,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  onboardingSubtitle: {
    fontSize: 16,
    color: '#94A3B8',
    marginBottom: 24,
    textAlign: 'center',
  },
  inputContainer: {
    width: '100%',
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#CBD5E1',
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 15,
    fontSize: 16,
    color: '#F1F5F9',
    backgroundColor: '#12121E',
  },
  pickerContainer: {
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 14,
    backgroundColor: '#12121E',
    overflow: 'hidden',
  },
  pickerContainerActive: {
    borderColor: 'rgba(167, 139, 250, 0.55)',
    backgroundColor: '#17172A',
  },
  picker: {
    height: 50,
    color: '#F1F5F9',
  },
  selectedStatePill: {
    marginTop: 10,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(103, 232, 249, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(103, 232, 249, 0.28)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  selectedStateFlag: {
    width: 22,
    height: 14,
    borderRadius: 2,
    marginRight: 8,
    backgroundColor: '#0F172A',
  },
  selectedStatePillText: {
    marginLeft: 6,
    color: '#67E8F9',
    fontSize: 12,
    fontWeight: '700',
  },
  dateButton: {
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 15,
    backgroundColor: '#12121E',
    justifyContent: 'center',
  },
  dateText: {
    fontSize: 16,
    color: '#F1F5F9',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1A1A2A',
    borderRadius: 20,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#F1F5F9',
    marginBottom: 20,
  },
  modalCloseButton: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#8B5CF6',
    borderRadius: 12,
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  modalCloseText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  inputHint: {
    fontSize: 12,
    color: '#475569',
    marginTop: 6,
  },
  onboardingOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#12121E',
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    width: '100%',
  },
  onboardingOptionSelected: {
    borderColor: '#8B5CF6',
    backgroundColor: 'rgba(139, 92, 246, 0.12)',
  },
  optionIcon: {
    width: 50,
    height: 50,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  optionIconText: {
    fontSize: 28,
  },
  optionContent: {
    flex: 1,
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#F1F5F9',
    marginBottom: 4,
  },
  optionDesc: {
    fontSize: 13,
    color: '#64748B',
  },
  studyPlanPreview: {
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
    borderRadius: 16,
    padding: 18,
    marginTop: 20,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
  },
  studyPlanTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#A78BFA',
    marginBottom: 8,
  },
  studyPlanText: {
    fontSize: 14,
    color: '#F1F5F9',
    fontWeight: '600',
  },
  studyPlanSmall: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 8,
  },
  onboardingActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },

  // ─── Test Details ─────────────────────────────────────────────────────────────
  testDetailsCard: {
    backgroundColor: '#12121E',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderLeftWidth: 3,
    borderLeftColor: '#8B5CF6',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  studyPlanCard: {
    backgroundColor: 'rgba(52, 211, 153, 0.08)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderLeftWidth: 3,
    borderLeftColor: '#34D399',
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.2)',
  },
  studyPlanHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  studyPlanCardTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#6EE7B7',
    marginLeft: 6,
  },
  studyPlanCardLine: {
    fontSize: 14,
    color: '#34D399',
    marginBottom: 2,
  },
  studyPlanCardHint: {
    fontSize: 12,
    color: '#2DD4BF',
    marginTop: 6,
  },
  resumeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(52, 211, 153, 0.12)',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.3)',
  },
  resumeButtonTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#6EE7B7',
  },
  resumeButtonSubtitle: {
    fontSize: 12,
    color: '#2DD4BF',
    marginTop: 2,
  },
  boostsCard: {
    marginBottom: 16,
    backgroundColor: 'rgba(139, 92, 246, 0.08)',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
  },
  boostsHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  boostsTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#C4B5FD',
  },
  boostsSubtitle: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: '#A78BFA',
    maxWidth: 260,
  },
  boostsGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  boostMetricCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.15)',
  },
  boostMetricLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#A78BFA',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  boostMetricValue: {
    marginTop: 6,
    fontSize: 26,
    fontWeight: '900',
    color: '#F1F5F9',
  },
  boostMetricHint: {
    marginTop: 4,
    fontSize: 12,
    color: '#64748B',
  },
  rewardedHomeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#8B5CF6',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 6,
  },
  rewardedHomeButtonDisabled: {
    opacity: 0.5,
  },
  rewardedHomeTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#fff',
  },
  rewardedHomeSubtitle: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.65)',
    marginTop: 2,
  },
  homeKpiCard: {
    marginBottom: 16,
    backgroundColor: 'rgba(6, 182, 212, 0.08)',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(6, 182, 212, 0.2)',
  },
  homeKpiHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  homeKpiTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#67E8F9',
  },
  homeKpiMetricsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  homeKpiMetricBox: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(6, 182, 212, 0.15)',
  },
  homeKpiMetricLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#2DD4BF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  homeKpiMetricValue: {
    marginTop: 6,
    fontSize: 24,
    fontWeight: '900',
    color: '#F1F5F9',
  },
  homeKpiInsight: {
    fontSize: 12,
    lineHeight: 18,
    color: '#67E8F9',
    marginTop: 2,
  },
  countdownBadge: {
    marginTop: 8,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(139, 92, 246, 0.15)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  countdownBadgeText: {
    marginLeft: 4,
    fontSize: 11,
    fontWeight: '800',
    color: '#C4B5FD',
  },

  // ─── Admin ────────────────────────────────────────────────────────────────────
  adminCard: {
    backgroundColor: '#12121E',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  adminCardTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#F1F5F9',
    marginBottom: 12,
  },
  analyticsLine: {
    fontSize: 13,
    color: '#94A3B8',
    marginBottom: 4,
  },
  revenueSummaryBox: {
    marginTop: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  revenueLine: {
    fontSize: 13,
    color: '#CBD5E1',
    marginTop: 2,
  },
  trendChartRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 8,
    marginBottom: 4,
  },
  trendBarColumn: {
    flex: 1,
    alignItems: 'center',
  },
  trendValueLabel: {
    fontSize: 10,
    color: '#64748B',
    marginBottom: 4,
  },
  trendBarTrack: {
    width: 20,
    height: 100,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  trendBarFill: {
    width: '100%',
    backgroundColor: '#8B5CF6',
    borderRadius: 999,
  },
  trendBarLabel: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 6,
  },
  revenueBandLine: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 6,
    lineHeight: 18,
  },
  monthlyToggleButton: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(139, 92, 246, 0.12)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.25)',
  },
  monthlyToggleText: {
    marginLeft: 4,
    color: '#A78BFA',
    fontSize: 12,
    fontWeight: '700',
  },
  revenueTotal: {
    fontSize: 15,
    fontWeight: '800',
    color: '#34D399',
    marginTop: 8,
  },
  revenueHint: {
    fontSize: 11,
    color: '#475569',
    marginTop: 6,
  },
  adminMetricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  adminMetricLabelBlock: {
    flex: 1,
    paddingRight: 12,
  },
  adminMetricLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#F1F5F9',
  },
  adminMetricSubtext: {
    marginTop: 2,
    fontSize: 11,
    color: '#64748B',
  },
  adminMetricValue: {
    fontSize: 13,
    fontWeight: '800',
    color: '#34D399',
  },
  adminSuggestionBadge: {
    marginTop: 8,
    marginBottom: 2,
    alignSelf: 'flex-start',
    flexDirection: 'row',
  adminCopyFeedback: {
    marginTop: 8,
    color: '#86EFAC',
    fontWeight: '700',
  },
  adminCopyFeedbackError: {
    color: '#FCA5A5',
  },
    alignItems: 'center',
    backgroundColor: 'rgba(52, 211, 153, 0.12)',
    borderRadius: 999,
    paddingHorizontal: 10,
  homeScrollTopButton: {
    position: 'absolute',
    right: 16,
    bottom: 24,
    backgroundColor: 'rgba(139, 92, 246, 0.95)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(196, 181, 253, 0.8)',
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  homeScrollTopButtonText: {
    color: '#F8FAFC',
    fontSize: 12,
    fontWeight: '800',
  },
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.25)',
  },
  adminSuggestionBadgeText: {
    marginLeft: 6,
    fontSize: 11,
    fontWeight: '700',
    color: '#34D399',
  },
  testDetailsContent: {
    flex: 1,
    flexDirection: 'row',
    gap: 16,
  },
  testDetailsLabel: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  testDetailsValue: {
    fontSize: 13,
    color: '#F1F5F9',
    fontWeight: '600',
    marginTop: 2,
  },
  testDetailsSeparator: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  testDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  // ─── Generic helpers ──────────────────────────────────────────────────────────
  screenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
    marginTop: 4,
  },
  spacer: {
    flex: 1,
  },
  helperTextBox: {
    backgroundColor: 'rgba(56, 189, 248, 0.1)',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.2)',
  },
  helperText: {
    fontSize: 13,
    color: '#7DD3FC',
    flex: 1,
    lineHeight: 18,
  },

  // ─── QuizScreen: question card ────────────────────────────────────────────────
  questionCard: {
    backgroundColor: '#12121E',
    borderRadius: 20,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  questionImage: {
    width: '100%',
    height: 180,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  multiAnswerHint: {
    fontSize: 12,
    color: '#A78BFA',
    fontStyle: 'italic',
    marginTop: 6,
    lineHeight: 16,
  },

  // ─── QuizScreen: mode badges ──────────────────────────────────────────────────
  smartQueueBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(56, 189, 248, 0.12)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
    alignSelf: 'flex-start',
    marginTop: 6,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.25)',
  },
  smartQueueBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#7DD3FC',
  },
  focusModeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(52, 211, 153, 0.12)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
    alignSelf: 'flex-start',
    marginTop: 6,
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.25)',
  },
  focusModeBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6EE7B7',
  },

  // ─── Spatial Route: 3D path scaffold ─────────────────────────────────────────
  threeDPathContainer: {
    flex: 1,
    minHeight: 320,
  },
  threeDPathContent: {
    paddingVertical: 18,
    paddingHorizontal: 6,
    gap: 10,
  },
  threeDIsland: {
    height: 132,
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.20)',
    justifyContent: 'center',
    shadowColor: '#0EA5E9',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  threeDIslandTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#E2E8F0',
  },
  threeDIslandSubtitle: {
    marginTop: 4,
    fontSize: 12,
    color: '#94A3B8',
  },
  threeDIslandUrgency: {
    marginTop: 8,
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: '700',
    color: '#FDBA74',
    backgroundColor: 'rgba(251, 146, 60, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(251, 146, 60, 0.35)',
  },
  homeBetaFallbackBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(180, 83, 9, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.45)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 8,
  },
  homeBetaFallbackBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FDE68A',
  },

  // ─── QuizScreen: ADHD option buttons ──────────────────────────────────────────
  adhd_optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#12121E',
    borderRadius: 18,
    padding: 18,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  adhd_optionCorrect: {
    borderColor: '#34D399',
    backgroundColor: 'rgba(52, 211, 153, 0.1)',
  },
  adhd_optionWrong: {
    borderColor: '#F87171',
    backgroundColor: 'rgba(248, 113, 113, 0.1)',
  },
  adhd_optionSelected: {
    borderColor: '#8B5CF6',
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
  },
  dotCorrect: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#34D399',
    marginRight: 10,
    shadowColor: '#34D399',
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  dotWrong: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#F87171',
    marginRight: 10,
    shadowColor: '#F87171',
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  adhd_optionText: {
    flex: 1,
    fontSize: 15,
    color: '#CBD5E1',
    lineHeight: 22,
    fontWeight: '600',
  },
  adhd_textCorrect: {
    color: '#6EE7B7',
    fontWeight: '800',
  },
  adhd_textWrong: {
    color: '#FCA5A5',
    textDecorationLine: 'line-through',
  },

  // ─── QuizScreen: feedback section ─────────────────────────────────────────────
  adhd_feedbackBox: {
    backgroundColor: '#14141F',
    borderRadius: 20,
    padding: 18,
    marginTop: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  feedbackHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 12,
  },
  feedbackEmoji: {
    fontSize: 28,
    lineHeight: 34,
  },
  feedbackMessage: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
  },
  feedbackSuccess: {
    color: '#6EE7B7',
  },
  feedbackInfo: {
    color: '#FDBA74',
  },

  // ─── QuizScreen: correct answer box ───────────────────────────────────────────
  correctAnswerBox: {
    backgroundColor: 'rgba(52, 211, 153, 0.1)',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#34D399',
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.2)',
  },
  correctAnswerLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#34D399',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  correctAnswerText: {
    fontSize: 15,
    color: '#6EE7B7',
    fontWeight: '700',
    lineHeight: 22,
  },
  alternateAnswersBox: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(52, 211, 153, 0.2)',
  },
  alternateAnswersLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#34D399',
    marginBottom: 4,
  },
  alternateAnswerItem: {
    fontSize: 14,
    color: '#6EE7B7',
    marginBottom: 2,
    lineHeight: 20,
  },

  // ─── QuizScreen: explanation & continue ───────────────────────────────────────
  adhd_explanationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(139, 92, 246, 0.15)',
    borderRadius: 14,
    padding: 13,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.3)',
  },
  adhd_explanationButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#A78BFA',
  },
  adhd_explanationBox: {
    backgroundColor: 'rgba(139, 92, 246, 0.08)',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#8B5CF6',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.15)',
  },
  adhd_explanationText: {
    fontSize: 13,
    color: '#C4B5FD',
    lineHeight: 20,
  },
  adhd_continueButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 18,
    padding: 18,
    alignItems: 'center',
    marginTop: 8,
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 6,
  },
  adhd_continueButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#fff',
  },

  // ─── HomeScreen: ADHD focus presets ───────────────────────────────────────────
  focusPresetCard: {
    backgroundColor: '#12121E',
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  focusPresetTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#F1F5F9',
    marginBottom: 4,
  },
  focusPresetSubtitle: {
    fontSize: 13,
    color: '#64748B',
    marginBottom: 14,
  },
  focusPresetRow: {
    flexDirection: 'row',
    gap: 10,
  },
  focusPresetButton: {
    flex: 1,
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.25)',
  },
  focusPresetButtonTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#A78BFA',
    marginBottom: 2,
  },
  focusPresetButtonMeta: {
    fontSize: 11,
    color: '#8B5CF6',
    textAlign: 'center',
    fontWeight: '600',
  },

  // ─── ReviewScreen: bonus / rewarded ad ────────────────────────────────────────
  bonusCard: {
    backgroundColor: 'rgba(251, 191, 36, 0.08)',
    borderColor: 'rgba(251, 191, 36, 0.25)',
    borderWidth: 1,
  },
  bonusText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FCD34D',
    marginBottom: 10,
    lineHeight: 20,
  },
  rewardedOfferStack: {
    gap: 10,
  },
  rewardedAdButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#8B5CF6',
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 12,
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  rewardedAdButtonSecondary: {
    backgroundColor: '#0D9488',
    shadowColor: '#0D9488',
  },
  rewardedAdText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#fff',
  },
  reviewUpsellWaitCard: {
    backgroundColor: '#14141F',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  reviewUpsellHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  reviewUpsellTag: {
    backgroundColor: 'rgba(251, 191, 36, 0.2)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.35)',
  },
  reviewUpsellTagText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FBBF24',
  },

  // ─── MasteryMapScreen: action buttons ─────────────────────────────────────────
  masteryActionButtonLarge: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#8B5CF6',
    borderRadius: 18,
    padding: 16,
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 6,
  },
  masteryActionButtonGhost: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 18,
    padding: 16,
    borderWidth: 2,
    borderColor: 'rgba(139, 92, 246, 0.4)',
    backgroundColor: 'rgba(139, 92, 246, 0.06)',
  },
  masteryActionButtonGhostText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#A78BFA',
  },
  masterySmartQueueActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
    marginBottom: 12,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    marginVertical: 8,
  },
  testDetailLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  testDetailValue: {
    fontSize: 14,
    color: '#F1F5F9',
    fontWeight: '700',
    marginBottom: 4,
  },
});

export default styles;
