import { createContext } from 'react';

export const createDefaultAdRuntime = () => ({
  dayKey: '',
  dailyCount: 0,
  resumeCount: 0,
  quizCompleteCount: 0,
  quizCompleteOpportunityCount: 0,
  lastShownAt: 0,
  currentDayInterstitialShown: 0,
  currentDayRewardedCompleted: 0,
  freePackDayKey: '',
  freePackUnlocksToday: 0,
  freePackCooldownUntil: 0,
  comebackCampaign: {
    lastActiveDayKey: '',
    eligibleWindow: null,
    windows: {
      d2: {
        dayOffset: 2,
        eligible: false,
        lastEligibleDayKey: null,
        lastTriggeredAt: null,
        shownCount: 0,
        claimedCount: 0,
        lastClaimedAt: null,
      },
      d5: {
        dayOffset: 5,
        eligible: false,
        lastEligibleDayKey: null,
        lastTriggeredAt: null,
        shownCount: 0,
        claimedCount: 0,
        lastClaimedAt: null,
      },
      d10: {
        dayOffset: 10,
        eligible: false,
        lastEligibleDayKey: null,
        lastTriggeredAt: null,
        shownCount: 0,
        claimedCount: 0,
        lastClaimedAt: null,
      },
    },
  },
  history: [],
  offerVariants: {
    homeSprintOffer: 'control',
    homeSprintReward: 'standard',
    reviewBonusOffer: 'control',
    reviewWeakOffer: 'control',
  },
  pinnedOfferVariants: {},
  autoOfferWinners: {
    homeSprintOffer: null,
    homeSprintReward: null,
    reviewBonusOffer: null,
    reviewWeakOffer: null,
  },
  experimentCohorts: {
    revenueIntelligence: {
      cohort: null,
      overrideCohort: null,
      assignedAt: null,
      seed: '',
      bucket: null,
      holdoutPct: 20,
    },
  },
  offerVariantStats: {},
  analytics: {
    interstitialAttempts: 0,
    interstitialShown: 0,
    interstitialFailed: 0,
    interstitialSkippedCooldown: 0,
    interstitialSkippedDailyCap: 0,
    interstitialSkippedTriggerCap: 0,
    interstitialResumeShown: 0,
    interstitialQuizCompleteShown: 0,
    interstitialGenericShown: 0,
    interstitialQuizCompleteEligible: 0,
    interstitialQuizCompleteSkippedShortSession: 0,
    interstitialQuizCompleteSkippedLowScore: 0,
    interstitialQuizCompleteSkippedCadence: 0,
    rewardedAttempts: 0,
    rewardedCompleted: 0,
    rewardedFailedOrClosed: 0,
    rewardedHomeSprintAttempts: 0,
    rewardedSprintUnlocks: 0,
    rewardedReviewBonusAttempts: 0,
    rewardedBonusUnlocks: 0,
    rewardedReviewWeakAttempts: 0,
    rewardedReviewWeakUnlocks: 0,
    rewardedFreePackAttempts: 0,
    rewardedFreePackUnlocked: 0,
    rewardedFreePackBlockedDailyLimit: 0,
    rewardedFreePackBlockedCooldown: 0,
    rewardedFreePackFailed: 0,
    weakScoreUpsellEligible: 0,
    weakScoreUpsellShown: 0,
    comebackD2Triggered: 0,
    comebackD5Triggered: 0,
    comebackD10Triggered: 0,
    comebackD2Claimed: 0,
    comebackD5Claimed: 0,
    comebackD10Claimed: 0,
    focusStateEnterCount: 0,
    focusStateExitCount: 0,
    focusShieldPromptShownCount: 0,
    focusShieldActivatedCount: 0,
    interstitialSkippedFocusSuppression: 0,
    interstitialSkippedCinematicSafetyBuffer: 0,
    interstitialSkippedRolling10mCap: 0,
    interstitialQuizCompleteSkippedNoNaturalBreak: 0,
  },
  focusTelemetry: {
    focusVelocity: 0,
    accuracyStreak: 0,
    interactionLatencyMs: 0,
    sessionFatigueScore: 0,
    adSuppressionActive: false,
    adSuppressionUntil: 0,
    focusShieldUntil: 0,
    focusShieldEligible: false,
    focusShieldPromptShownForWindow: false,
    recoveryRewardedPrompt: false,
    focusStateSeen: false,
    focusEnteredAt: 0,
    focusExitedAt: 0,
    cinematicLandingAt: 0,
    interstitialShownAt: [],
  },
});

export const createDefaultMasteryMap = () => ({
  updatedAt: null,
  totalSessions: 0,
  totalQuestions: 0,
  byQuestion: {},
  topicDaily: {},
});

export const createDefaultUserProfile = () => ({
  name: '',
  email: '',
  avatarUri: '',
});

export const createDefaultSquadSync = () => ({
  teamId: null,
  teamName: '',
  inviteCode: '',
  weeklyGoal: {
    quizzes: 12,
    focusMinutes: 120,
  },
  weeklyChallenge: {
    id: 'founders-week',
    title: 'Founders Week Sprint',
    target: 20,
    progress: 0,
  },
  householdBoard: {
    items: [
      {
        id: 'board-1',
        title: 'Daily civics warmup (10 min)',
        assignedTo: 'self',
        completed: false,
        lastCompletedAt: null,
      },
      {
        id: 'board-2',
        title: 'Review one weak topic together',
        assignedTo: 'squad',
        completed: false,
        lastCompletedAt: null,
      },
    ],
  },
  streakChain: {
    currentDays: 0,
    bestDays: 0,
    lastActivityDay: null,
  },
  nudgeCooldownByMember: {},
  moderation: {
    rateBuckets: {},
    mutedActors: {},
    violationsByActor: {},
    escalationByActor: {},
    auditTrail: [],
  },
  season: {
    seasonId: null,
    weekKey: null,
    startsAt: null,
    endsAt: null,
    resetCadence: 'weekly',
    resetCount: 0,
    leaderboard: [],
    tierSummary: {
      bronze: 0,
      silver: 0,
      gold: 0,
      platinum: 0,
    },
    intentTransitionSummary: {
      totals: {
        changed: 0,
        unchanged: 0,
        entries: 0,
      },
      bySegment: {
        'high-intent': 0,
        warming: 0,
        'low-intent': 0,
        unknown: 0,
      },
      transitions: {},
    },
    archived: [],
  },
  syncMeta: {
    revision: 0,
    lastMutationAt: null,
    lastWriterDeviceId: 'local-device',
    fieldClock: {},
  },
  members: [],
  updatedAt: null,
});

export const AppDataContext = createContext({
  testDetails: null,
  setTestDetails: () => {},
  errorBank: [],
  addErrorItem: () => {},
  pausedSession: null,
  savePausedSession: () => {},
  clearPausedSession: () => {},
  maybeShowInterstitial: async () => false,
  adRuntime: createDefaultAdRuntime(),
  trackAdEvent: () => {},
  trackAppEvent: () => {},
  reportFocusInteraction: () => {},
  activateFocusShieldRewarded: async () => ({ ok: false }),
  recordCinematicLanding: () => {},
  getOfferVariant: () => 'control',
  setPinnedOfferVariant: () => {},
  setRevenueCohortOverride: () => {},
  resetOfferVariantStats: () => {},
  resetAdAnalytics: () => {},
  unlockDailyFreePack: async () => ({ ok: false }),
  claimComebackReward: async () => ({ ok: false }),
  masteryMap: createDefaultMasteryMap(),
  recordMasterySession: () => {},
  resetMasteryMap: () => {},
  userProfile: createDefaultUserProfile(),
  updateUserProfile: () => {},
  squadSync: createDefaultSquadSync(),
  createSquad: () => {},
  refreshSquadInviteCode: () => {},
  updateSquadWeeklyGoal: () => {},
  updateSquadChallengeProgress: () => {},
  toggleHouseholdBoardItem: () => {},
  recordParentChildNudge: () => {},
  enforceModerationPolicy: async () => ({ allowed: true }),
  refreshSquadFromRemote: async () => ({ ok: false }),
  runModerationAdminAction: async () => ({ ok: false }),
});
